<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="3" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="584" started-at="2019-01-02T11:28:02Z" finished-at="2019-01-02T11:28:02Z">
    <groups>
      <group name="Smoke">
        <method signature="ExcelTest.TestExcel1()[pri:0, instance:testcases.ExcelTest@3c0ecd4b]" name="TestExcel1" class="testcases.ExcelTest"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="Test" duration-ms="584" started-at="2019-01-02T11:28:02Z" finished-at="2019-01-02T11:28:02Z">
      <class name="testcases.ExcelTest">
        <test-method status="PASS" signature="TestExcel1()[pri:0, instance:testcases.ExcelTest@3c0ecd4b]" name="TestExcel1" duration-ms="537" started-at="2019-01-02T11:28:02Z" finished-at="2019-01-02T11:28:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestExcel1 -->
      </class> <!-- testcases.ExcelTest -->
      <class name="testcases.AbsenceManagementTest">
        <test-method status="FAIL" signature="endTest()[pri:0, instance:testcases.AbsenceManagementTest@553f17c]" name="endTest" is-config="true" duration-ms="0" started-at="2019-01-02T11:28:02Z" finished-at="2019-01-02T11:28:02Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at testcases.AbsenceManagementTest.endTest(AbsenceManagementTest.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- testcases.AbsenceManagementTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
